project_id = "btnyenoxsjtuydpzbapq"

[functions.checkout]
enabled = true
verify_jwt = false
import_map = "./functions/checkout/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/checkout/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/checkout/*.html" ]

[functions.mondial-relay]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
