[build]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  publish = "dist"
  functions = "functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  included_files = ["functions/**"]
  external_node_modules = ["axios"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
