[build]
  command = "npm install --legacy-peer-deps && npm run build" # Installation propre avant build
  functions = "functions"  # Dossier où sont stockées les fonctions Netlify
  node_bundler = "esbuild"  # Assure une meilleure compatibilité

[functions]
  included_files = ["functions/**"]  # Force l'inclusion des fichiers
  external_node_modules = ["axios"]  # Inclut axios dans les dépendances Netlify

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200
