[build]
  command = "npm run build"  # Assure-toi que le build est bien exécuté
  functions = "functions"  # Ton dossier de fonctions est directement "functions/"

[functions]
  external_node_modules = ["axios"]  # Ajout des dépendances nécessaires

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200
