[build]
  command = "npm install"  # S'assurer que les dépendances sont installées
  functions = "netlify/functions"

[functions]
  external_node_modules = ["axios"]

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200
